import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: "Portafolio | Marcos",
  description: "Portafolio de Marcos",
};



// 1. Importa el Provider que acabamos de crear (asegúrate de que la ruta sea correcta según donde creaste la carpeta)
import { LanguageProvider } from "./context/LanguageContext";
import "./globals.css";


export default function RootLayout({ children }) {
  return (
    <html lang="es" className="scroll-smooth">
      <body className="bg-black text-white">
        {/* 2. Envuelve los children con el Provider */}
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}





